export const BASKETSACTIONS = {
    SORT_COLLECTION: 'baskets/SORT_COLLECTION',
    LOAD_STRATEGIES: 'baskets/LOAD_STRATEGIES',
    TRASH_STRATEGIES: 'baskets/TRASH_STRATEGIES',
    SET_TRASH_STRATEGIES: 'baskets/SET_TRASH_STRATEGIES',
};

export const MARKETDETAILACTIONS = {
    SET_SYMBOLS: 'marketdetail/SET_SYMBOLS'
}