# This is a basic workflow to help you get started with Actions

name: Production Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ production-disabled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2
          
      - name: Deploy Changes
        uses: fifsky/ssh-action@master
        with:
          command: |

            deploymentScript=${{ secrets.PRODUCTION_SCRIPT }}
            sudo bash $deploymentScript
            
          host: ${{ secrets.DEPLOYMENT_SERVER }}
          user: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY}}
          args: '-tt'
          